name: servidor_ci

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar Repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar la Build
        run: npm run build

      - name: Correr los tests
        run: npm test

      - name: Crear PR a main
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b pr-from-develop
          git push https://oauth2:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} pr-from-develop
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               -d '{"title":"PR: Merge develop into main","head":"pr-from-develop","base":"main"}' \
               -H "Content-Type: application/json" \
               https://api.github.com/repos/${{ github.repository }}/pulls





